use_frameworks!

platform :ios, '9.0'
post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
end
target 'LearnPforTest_Example' do
  pod 'LearnPforTest', :path => '../'


  target 'LearnPforTest_Tests' do
    inherit! :search_paths
    

     
  end
end

      

